Use notify based approach for gem documentation preference
This changes the approach used to install Ruby version as currently
everytime a new Ruby version is installed an error occurs and then only
succeeds on the subsequent puppet run.

As far as I understand the issue with the existing approach is that
puppet doesn't run everything in a procedural order instead it uses the
script to decide what to do and then determines the order. Thus we were
getting errors that a directory wasn't available:

```
Error: Cannot create /usr/lib/rbenv/versions/2.5.1/etc; parent directory /usr/lib/rbenv/versions/2.5.1 does not exist
Error: /Stage[main]/Govuk_rbenv::All/Rbenv::Version[2.5.1]/File[/usr/lib/rbenv/versions/2.5.1/etc]/ensure: change from absent to directory failed: Cannot create /usr/lib/rbenv/versions/2.5.1/etc; parent directory /usr/lib/rbenv/versions/2.5.1 does not exist
Notice: /Stage[main]/Govuk_rbenv::All/Rbenv::Version[2.5.1]/File[/usr/lib/rbenv/versions/2.5.1/etc/gemrc]: Dependency File[/usr/lib/rbenv/versions/2.5.1/etc] has failures: true
Warning: /Stage[main]/Govuk_rbenv::All/Rbenv::Version[2.5.1]/File[/usr/lib/rbenv/versions/2.5.1/etc/gemrc]: Skipping because of failed dependencies
```

This instead changes the process to use puppet notify so that
these actions occur in a determined order. This allows the parent
directory to exist prior to setting up the configuration of gem
documentation.